SECURE_CROSS_ORIGIN_OPENER_POLICY = None
"""
Django settings for spplus project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import datetime
from django.conf.global_settings import DATE_INPUT_FORMATS


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _csv_env(name: str) -> list[str]:
    value = os.getenv(name, "")
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-00xm)0p^613c5z@0&+^56uf(hm@w+pr5qi8s$#^o0ul^rtt&r_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ 'salespiee.com',
    'www.salespiee.com',
    '127.0.0.1',
    'localhost',
    '192.168.1.44',
    '192.168.1.94',
    '::1',
    '2406:da1a:4f2:9f00:f030:23ce:5c41:2936',
] + _csv_env('EXTRA_ALLOWED_HOSTS')

DATE_INPUT_FORMATS = ['%d-%m-%Y'] 

AUTH_USER_MODEL = "sales.User"
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    
    
]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#      'django.middleware.common.CommonMiddleware',
# ]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',           # 1st - Handle CORS/OPTIONS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',       # After Session
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spplus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [
            os.path.join(BASE_DIR, 'build'),  # Add this line to point to the React build directory
            os.path.join(BASE_DIR, 'templates'),  # Keep this for other templates if needed
        ],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spplus.wsgi.application'


def _is_running_in_docker() -> bool:
    return os.path.exists('/.dockerenv') or os.getenv('RUNNING_IN_DOCKER') == '1'


DB_ENGINE = os.getenv('DB_ENGINE', 'postgres' if _is_running_in_docker() else 'sqlite').lower()

if DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'salescrm'),
            'USER': os.getenv('DB_USER', 'salespie'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'salespie123'),
            'HOST': os.getenv('DB_HOST', 'db' if _is_running_in_docker() else '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432' if _is_running_in_docker() else '5433'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_NAME', BASE_DIR / 'db.sqlite3'),
        }
    }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'ROTATE_REFRESH_TOKEN' :True,
    'BLACKLIST_AFTER_ROTATION' : True
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # For collected static files

# Serve both React's static files and other assets like manifest.json and index.html
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'build/static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    # 'http://localhost:5173',      # Vite dev server
    # 'http://localhost:3000',      # React build  
    # 'http://127.0.0.1:5173',
    # 'http://127.0.0.1:3000',
    # 'http://localhost:8000',      # Backend itself
   
    'http://localhost:5173',
    'http://127.0.0.1:5173', 
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8001',
    'http://192.168.1.44:8001',
    'http://192.168.1.94:8001',
    'http://localhost:8000',
] + _csv_env('EXTRA_CSRF_TRUSTED_ORIGINS')


CORS_ALLOWED_ORIGINS = [
    # 'http://localhost:5173',
    # 'http://localhost:3000', 
    # 'http://127.0.0.1:5173',
    # 'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:8001',
    'http://192.168.1.44:8001',
    'http://192.168.1.94:8001',
    'http://localhost:8000'
] + _csv_env('EXTRA_CORS_ALLOWED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'anaghashajeevan2001@gmail.com'       # ← your Gmail address
EMAIL_HOST_PASSWORD = 'gbbyxiwjffifphkg'    # ← Gmail App Password (NOT your Gmail login password)
DEFAULT_FROM_EMAIL = 'anaghashajeevan2001@gmail.com'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False  # Development only
CSRF_COOKIE_SAMESITE = 'Lax'


GROQ_API_KEY = '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'
