# Generated by Django 5.2.8 on 2025-11-26 09:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_points', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lead_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='sales.lead')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_pics', to='sales.leadworkspace')),
            ],
        ),
    ]
