# Generated by Django 5.2.8 on 2025-11-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_leadworkspace_workspacepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacepic',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='LeadWorkspace',
        ),
        migrations.DeleteModel(
            name='WorkspacePIC',
        ),
    ]
