# Generated by Django 5.1 on 2026-04-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_workspacepic_workspace_delete_leadworkspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity_Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup', models.CharField(blank=True, max_length=255, null=True)),
                ('followup_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('add_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_followup', to='sales.opportunity')),
            ],
        ),
    ]
