# Generated by Django 5.1 on 2026-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_opportunity_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sales_type',
            field=models.CharField(blank=True, choices=[('Repeat', 'Repeat'), ('Upselling', 'Upselling'), ('Cross selling', 'Cross selling')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sales_type_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
