# Generated by Django 5.1 on 2026-04-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_budget_budgetallocation_spendentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='spendentry',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='spendentry',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='spendentry',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetAllocation',
        ),
        migrations.DeleteModel(
            name='SpendEntry',
        ),
    ]
