# Generated by Django 5.1 on 2026-04-10 04:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_budgetallocation_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('currency', models.CharField(choices=[('INR', '₹ INR'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP')], default='INR', max_length=5)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_deal_count', models.IntegerField(default=0)),
                ('max_budget_per_deal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('tools', 'Tools & Software'), ('travel', 'Travel'), ('events', 'Events'), ('headcount', 'Headcount / Commissions'), ('other', 'Other')], max_length=50)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alert_threshold', models.IntegerField(default=80)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sales.budget')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=50)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deals_closed', models.IntegerField(default=0)),
                ('recorded_at', models.DateField(default=datetime.date.today)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sales.budget')),
            ],
        ),
    ]
