# Generated by Django 5.1 on 2026-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_budget_budgetcategory_budgetsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='category_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='icon',
            field=models.CharField(default='📦', max_length=10),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
