# Generated by Django 5.1 on 2026-04-14 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_budgetcategory_category_label_budgetcategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='budgetsnapshot',
            options={'ordering': ['-snapshot_date']},
        ),
        migrations.RemoveField(
            model_name='budgetsnapshot',
            name='recorded_at',
        ),
        migrations.AddField(
            model_name='budget',
            name='deals_closed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 — Apr, May, Jun'), ('Q2', 'Q2 — Jul, Aug, Sep'), ('Q3', 'Q3 — Oct, Nov, Dec'), ('Q4', 'Q4 — Jan, Feb, Mar')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'name')},
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=5),
        ),
        migrations.AlterField(
            model_name='budget',
            name='max_budget_per_deal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='revenue_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetsnapshot',
            name='period_label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetsnapshot',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetsnapshot',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='allocated',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='category_label',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='spent',
        ),
        migrations.CreateModel(
            name='BudgetPeriodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=20)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_entries', to='sales.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_entries', to='sales.budgetcategory')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('budget', 'category', 'month')},
            },
        ),
    ]
