# Generated by Django 5.1 on 2026-04-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_budget_options_alter_budgetcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='deals_closed',
        ),
    ]
