# Generated by Django 5.1 on 2026-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_visitingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
