# Generated by Django 5.1 on 2026-04-27 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='total_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='selected_month',
            field=models.CharField(blank=True, choices=[('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BudgetSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='sales.budgetcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetperiodentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetperiodentry',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_entries', to='sales.budgetsubcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetperiodentry',
            unique_together={('budget', 'category', 'subcategory', 'month')},
        ),
    ]
