# Generated by Django 5.1 on 2026-04-28 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_budget_total_budget_budget_selected_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GlobalSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='sales.globalcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
