# Generated by Django 5.1 on 2026-05-06 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_globalcategory_globalsubcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetperiodentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetperiodentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_budget_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='budgetperiodentry',
            unique_together={('budget', 'category', 'subcategory', 'month', 'user')},
        ),
    ]
