# Generated by Django 5.1 on 2026-05-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_budgetperiodentry_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiodentry',
            name='spent',
        ),
    ]
