# Generated by Django 5.2.8 on 2026-05-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_performancetarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='implementation_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
