# Generated by Django 5.2.8 on 2026-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_opportunity_implementation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
