# Generated by Django 5.2.8 on 2026-05-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_formsettingsstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSettingsStore',
        ),
    ]
